# Generated by Django 5.2.9 on 2025-12-29 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحلقة')),
                ('time', models.CharField(max_length=50, verbose_name='وقت الحلقة')),
                ('location', models.CharField(max_length=100, verbose_name='المكان')),
            ],
            options={
                'verbose_name': 'حلقة',
                'verbose_name_plural': 'الحلقات',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم هاتف ولي الأمر')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quran_app.halaqa', verbose_name='الحلقة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('surah', models.CharField(max_length=100, verbose_name='السورة')),
                ('from_ayah', models.IntegerField(verbose_name='من آية')),
                ('to_ayah', models.IntegerField(verbose_name='إلى آية')),
                ('grade', models.CharField(choices=[('ممتاز', 'ممتاز'), ('جيد جداً', 'جيد جداً'), ('جيد', 'جيد'), ('مقبول', 'مقبول')], max_length=20, verbose_name='التقييم')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='quran_app.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل تسميع',
                'verbose_name_plural': 'سجلات التسميع',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('specialization', models.CharField(max_length=100, verbose_name='التخصص/الإجازة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
            },
        ),
        migrations.AddField(
            model_name='halaqa',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaqat', to='quran_app.teacher', verbose_name='المعلم'),
        ),
    ]
