# Generated by Django 5.2.9 on 2025-12-29 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqa',
            name='days',
            field=models.CharField(choices=[('يومي', 'يومي'), ('سبت-اثنين-أربعاء', 'سبت-اثنين-أربعاء'), ('أحد-ثلاثاء-خميس', 'أحد-ثلاثاء-خميس')], default='يومي', max_length=50, verbose_name='أيام الحلقة'),
        ),
        migrations.AddField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المعلم'),
        ),
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ التسجيل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الانضمام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halaqa',
            name='time',
            field=models.TimeField(verbose_name='وقت الحلقة'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='from_ayah',
            field=models.PositiveIntegerField(verbose_name='من آية'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='to_ayah',
            field=models.PositiveIntegerField(verbose_name='إلى آية'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('غائب', 'غائب'), ('مستأذن', 'مستأذن')], max_length=10, verbose_name='الحالة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='quran_app.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
